# Generated by Django 4.2.1 on 2023-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cantante', models.CharField(max_length=200)),
                ('duracion', models.IntegerField()),
                ('album', models.CharField(max_length=200)),
            ],
        ),
    ]
